### ISSUE TITLE
unable to equip items bought for justice/valor points - Cata Classic

### ISSUE THREAD

**Issue by telias82** [KyrosKrane/AnnoyingPopupRemover#46]
the dialog just never appears (which is fine?) and the item wont go into the slot, unless i turn this addon off. It makes trying to equip anything a bit cumbersome as we have to turn off the addon, equip the new item, then turn it back on to block all the annoying stuff again.

**Comment by telias82** [comment]
ok it worked this time though. 

![image](https://github.com/KyrosKrane/AnnoyingPopupRemover/assets/55420496/3bf26443-ed55-4abd-b775-040ed4567e51)

**Comment by telias82** [comment]
[02:56] APR Debug: At load,  HideBind  is  false 
[02:56] APR Debug: At load,  HideMail  is  true 
[02:56] APR Debug: in APR.Modules['mail'].HidePopup, printconfirm is false, ForceHide is true 
[02:56] APR Debug: APR.DB.PrintStartupMessage is  false

**Comment by KyrosKrane** [comment]
I've been working on some changes that should fix a lot of the issues that are coming up. This new version will only hide the dialog if it can actually accept it for you; otherwise it leaves it alone. Please give it a try with a brand new justice or valor item. If your setting is enabled, it should let you equip without a confirmation, and if the setting is off, it should still show you the confirmation box.

https://github.com/KyrosKrane/AnnoyingPopupRemover/releases/download/v20.3.0-alpha2/AnnoyingPopupRemover-v20.3.0-alpha2.zip

**Comment by telias82** [comment]
seems to be working, how do i stop the debugging now?

**Comment by KyrosKrane** [comment]
The fix will be in the next released version. You can update to that, and it will turn the debug messages off automatically. It should be out later today or tomorrow.

In the meantime, you can turn debug messages off with this command, but you have to do it on each login:
`/apr debug`

**Comment by KyrosKrane** [comment]
This was fixed with v20.3.0

**Comment by telias82** [comment]
I’m still seeing issues with it, where if I reload it works though. Not sure what’s up. On Jun 6, 2024, at 10:04 PM, KyrosKrane Sylvanblade ***@***.***> wrote:﻿
This was fixed with v20.3.0

**Comment by KyrosKrane** [comment]
Unfortunately I introduced a new bug with v20.3.0. It's fixed in v20.4.0 and later. Sorry about that!
